#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const pkg = require('../package.json');

const finds = [

`
import redux from 'redux';
import effects from 'redux-saga/effects';
import immer from 'immer';
`.trim(),

'immer.default'

];

const replaces = [

`
import * as redux from 'redux';
import * as effects from 'redux-saga/effects';
import immer from 'immer';
`.trim(),

'immer'

]


const filepath = path.resolve(__dirname, '..', pkg.module);

const contents = fs.readFileSync(filepath).toString();

let newContents = contents;

for (const i in finds) {

    const find = finds[i];
    const replace = replaces[i];

    newContents = newContents.replace(find, replace);
}


fs.writeFileSync(filepath, newContents);