#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const pkg = require('../package.json');

const findAndReplace = (path, entries) => {

    fs.writeFileSync(
        path,
        entries.reduce(
            (content, [find, replace]) => content.replace(find, replace),
            fs.readFileSync(path).toString()
        )
    );
}

const esImports = [

`
import redux from 'redux';
import effects from 'redux-saga/effects';
import immer from 'immer';
`.trim(),

`
import * as redux from 'redux';
import * as effects from 'redux-saga/effects';
import * as immer from 'immer';
`.trim()

];

findAndReplace(
    path.resolve(__dirname, '..', pkg.module),
    [esImports]
);

// const cjsImmer = [
//     'immer["default"]',
//     'immer'
// ];

// findAndReplace(
//     path.resolve(__dirname, '..', pkg.main),
//     [cjsImmer]
// );
